### ISSUE TITLE
Enforce time limit on each search in slskd, to prevent stuck soularr

### ISSUE THREAD

**Issue by yroyathon** [mrusse/soularr#41] opened 2024-11-05 19:23 UTC
I've mostly had a nice set-it-and-forget-it relationship with soularr since i've set it up, it's been great.  

But lately I've noticed that either soularr is getting stuck and/or slskd is getting stuck, when they are doing a search for a specific album.  I'm not sure which is at fault.  But I think it would be helpful to the app to enforce some kind of time limit for each individual search, that way it doesn't get stuck and halt the entire script.  I noticed my soularr (which runs 2x/day) was still running/waiting for a single search result from over a day and a half later.  In slskd it was still searching for that one result too.
I think once you hit the time limit for a single search, cancelling or ending the search if possible would be good.  But if not, simply having soularr move onto the next search would be fine.  If it's truly an slskd problem and soularr couldn't fix it anyways, then just moving on and not creating a new problem of a stuck soularr would a good path forward.  Occasionally, I can manually deal with stuck slskd searches, if slskd is truly at fault at creating those.

**Comment by CrimsonFlash** [comment] 2024-11-06 13:46
Adding onto this, it would be nice to have a time limit for downloading from each user as well.

Often, I'll check and either a download is stuck or the queue is something crazy like 1000+. So having it time-out and force cancel the downloads from those stuck users would help keep this more hands-off.

**Comment by mrusse** [comment] 2024-11-06 14:02
Both of these are on my todo list when I have some time. As for the stuck searches that never end it is definitely a Slskd bug since I am already setting the max search time to whatever you set `search_timeout` to in the config file (5 sec default). I am still planning to make a workaround for it on Soularr's side to detect these stuck searches.

**Comment by yroyathon** [comment] 2024-11-06 16:45
I get it, competing priorities.  I will make a workaround script that detects a long running soularr process in the docker container, and either kills the process or restarts the container.

**Comment by mrusse** [comment] 2024-11-14 14:56
I pushed a fix for this to the dev branch last night. The script now takes in new setting Slskd setting "stalled_timeout" this is the max number of seconds the script should run. If this time is reached then any unfinished downloads will be removed and the completed downloads will attempt to import. Please give it a try and let me know of any issues. I have pushed a docker image to `mrusse08/soularr:dev`

**Comment by yroyathon** [comment] 2024-11-14 18:14
Ok I'm running the dev image now, using 7200 as my stalled_timeout.  I'll let it run for days without my long-run-killer script running, and see if soularr ever gets stuck.

**Comment by mrusse** [comment] 2024-11-14 18:23
Awesome thanks!

**Comment by CrimsonFlash** [comment] 2024-11-14 20:24
Seems to be working well on my end, however I have set an override for 30 minutes, but it's using the default time of 60 minutes.

Unless I have the setting in the wrong area, this is my config:

[Search Settings]
stalled_timeout = 1800

**Comment by mrusse** [comment] 2024-11-14 20:34
@CrimsonFlash The setting needs to be under [Slskd]. The reason it is doing 60 is because if it cant find the setting in your config 60 is the default.

**Comment by yroyathon** [comment] 2024-11-17 01:44
It looks like it had a problem.  There's a bunch of downloads with mixed success/ongoing/errored.  I believe it's actually still running, waiting for queued/downloading downloads to finish.  It definitely did not cut things off after 7200 seconds.

The last lines in the log which appear to be from 20 hours ago are...
[INFO|soularr|L195] 2024-11-15T22:38:36-0600: Parsing result from user: findthelorax
[INFO|soularr|L58] 2024-11-15T22:38:36-0600: Found match from user: findthelorax for 10 tracks!
[INFO|soularr|L59] 2024-11-15T22:38:36-0600: Average sequence match ratio: 0.8424251238957121
[INFO|soularr|L60] 2024-11-15T22:38:36-0600: SUCCESSFUL MATCH
[INFO|soularr|L61] 2024-11-15T22:38:36-0600: -------------------

**Comment by mrusse** [comment] 2024-11-17 02:14
Can you verify that you are on the dev branch? Please also post the relevent section of your config file.

**Comment by yroyathon** [comment] 2024-11-17 15:24
Confirmed I am using the dev branch.  

[Slskd]
api_key = ****************************
host_url = http://host.docker.internal:5030/soulseek
#Slskd download directory. Should have set it up when installing Slskd.
download_dir = /soulseek_downloads
#Removes searches from Slskd after the search finishes.
delete_searches = True
#how many seconds the script should run, after which unfinished downloads are deleted, finished downloads are imported
stalled_timeout = 7200

**Comment by yroyathon** [comment] 2024-11-17 15:26
And it's been 13 hours, but the same set of downloads are in soulseek, and no new additions to the soularr log.

**Comment by mrusse** [comment] 2024-11-23 04:06
Just merged dev to main to try and get more eyes on this. It has been working fine on my end and I cannot duplicate your issue with the stalled_timeout. Other users have also reported it working well. If no other issues arise I will close this soon. Thanks.

**Comment by yroyathon** [comment] 2024-11-23 19:52
I am running the latest image you pushed now, we'll see how it goes.  Before this, I've had to cancel and cleanup several soularr runs that never got past the download stage.  Each time it seems to be caused by queued downloads, or downloads that are going very slowly, making the "download" stage stretch over hours and days.  This coupled with the stalled_timeout not being enforced.  But maybe it'll work this time around.  Maybe my stalled_timeout value is too high at 7200?  I just wanted to give soularr enough time to search through the hundreds of Wanted items currently in my Lidarr.

**Comment by CrimsonFlash** [comment] 2024-11-24 13:34
I've been running it non-stop since the dev branch update and have had no issues on my end. Been using an hour as my time-out duration.

**Comment by yroyathon** [comment] 2024-11-24 17:18
Mine is stuck again on a run from about 22 hours ago with a single active download hanging it up.  I'll try using 3600 or less as my stalled_timeout.

**Comment by mrusse** [comment] 2024-11-24 18:15
> Mine is stuck again on a run from about 22 hours ago with a single active download hanging it up.  I'll try using 3600 or less as my stalled_timeout.

Definitely report back with the results. Maybe a problem on your end with the image freezing up? I have tried timeouts longer than 3600 and things are working ok.

**Comment by yroyathon** [comment] 2024-11-25 17:34
It did get stuck again yesterday, but I cancelled a few of the stuck/slow/queued downloads in slskd and soularr immediately resumed and proceeded to the import step, which is great.  I'll remember that, cancelling downloads in soulseek is better than shutting the docker containers down.  

So I don't think soularr is stuck, or the image is freezing up (not exactly sure what that means tho).  Looking into soularr once a day to see if it's stuck and maybe cancelling long running downloads isn't the worst.  Since soularr resumes its job, I don't have to do as much file cleanup with all the abandoned downloads.

Maybe there keeps being an issue because my list of wanted files in Lidarr has grown unwieldy?  It was about 700 albums/eps/singles, now it's down to just under 500 thanks to a few successful soularr runs.  But I continue to gather evidence that the stalled_timeout is not being enforced.  Was it designed for active downloads as well as queued items?  I've seen both occur when things are stuck.

**Comment by yroyathon** [comment] 2024-11-25 18:09
Actually let me ask that explicitly, does the stalled_timeout prevent being stuck in a queued state for a download?  Versus an actively downloaded item. Maybe that's the issue for me.  Not being stuck in active downloads, but being stuck in someone's queue for hours and days.  If the time limit I set in stalled_timeout allowed me to exit out of a queue after the specified seconds, maybe that would solve my issue.  Unless it's already supposed to be doing that.

**Comment by mrusse** [comment] 2024-11-25 19:55
From what you are describing this sounds like it is behaving exactly as it should if you were running the version before I added the stalled timeout option. Yes it works for queued items. If something is still uncompleted in Slskd when the timeout is reached it should impot what is completed and then move on to the next run. 

To debug your setup further I just pushed an image `mrusse08/soularr:debug` can you switch to this image as it has some debug lines that will help see what the issue is.

It will first print out the stalled timeout setting so we can verify that is getting set right. For example: `[INFO|soularr|L565] 25/11/2024 12:50:07: STALLED TIMEOUT SET TO: 3600`. It will of course look different depending on your logging settings.

When all the current downloads are added it will also print: `[INFO|soularr|L373] 25/11/2024 14:45:02: Current timeout: 1130 - Stalled timeout: 3600` which shows what the current timeout is.

**Comment by mrusse** [comment] 2024-11-25 20:02
> Actually let me ask that explicitly, does the stalled_timeout prevent being stuck in a queued state for a download? Versus an actively downloaded item. Maybe that's the issue for me. Not being stuck in active downloads, but being stuck in someone's queue for hours and days. If the time limit I set in stalled_timeout allowed me to exit out of a queue after the specified seconds, maybe that would solve my issue. Unless it's already supposed to be doing that.

To be clear, how the stalled timeout works is once the current batch of downloads are added a timer starts and if it reaches the stalled timeout time the script will ignore any un-completed downloads and import the completed items. It is simple logic and does not actually care to check on the state of all the downloads. 

It sounds like you are running the script on your whole wanted list (hundreds of items) which is really not advised. I would instead recommend to run it with these search settings:

```
search_type = incrementing_page
number_of_albums_to_grab = 10
```

This will instead take a page (10 items by default) from your wanted list at a time. Each run through the page will increment.

**Comment by yroyathon** [comment] 2024-11-25 23:56
I'm not going to make any changes yet, but I did confirm that what I have running and been running does contain the stall logic.  See grepped stall logic below, and 640 lines matches the current copy of soularr.py .

I have no name!@soularr:/app$ cat soularr.py | grep stalled
        if(time_count > stalled_timeout):
    stalled_timeout = config['Slskd'].getint('stalled_timeout', 3600)
I have no name!@soularr:/app$ cat soularr.py | grep -i stall
        if(time_count > stalled_timeout):
            logger.info("Stall timeout reached! Removing stuck downloads...")
                        logger.error(f"Removing Stalled Download: Username: {username} Directory: {dir['name']}")
    stalled_timeout = config['Slskd'].getint('stalled_timeout', 3600)
I have no name!@soularr:/app$ wc -l soularr.py
640 soularr.py

**Comment by yroyathon** [comment] 2024-11-28 17:58
Well I did set search_type to incrementing_page and it's been running successfully for a few days now.  I don't know why it would enforce the stalled_timeouts this way but not the other way, but, I'm happy to not know as long as it works, I'll leave it this way from now on.  Running a single page of albums in Lidarr Wanted at a time, taking a short 300 second break, then moving onto the next page, etc.

**Comment by yroyathon** [comment] 2024-11-29 18:54
Well a day later and I found soularr stuck again, it was waiting over 12 hours for a single queued download.  So I will give your debug image a try and let you know what I see in the logs.  

If this isn't a priority to work on, I believe I can work around this issue.  I already have a script to detect a long running soularr and kill the process.  Instead of killing it, I could use the slskd api and just cancel queued and/or active downloads, that should allow soularr to continue since this is how I've been fixing it manually.  I am mostly confident that it's the queued downloads that are the issue, but we'll see.

**Comment by mrusse** [comment] 2024-11-29 18:58
It is a priority but it just seems like the issue is probably on your end. I have had no issues with the timeout and it getting stuck. Would be very curious to see your logs when you try the debug image though.

**Comment by yroyathon** [comment] 2024-11-29 19:02
Just curious, in what way could the issue be on my end, like an example (not disagreeing with you)?  Like some setting in slskd that is interfering with soularr?

**Comment by mrusse** [comment] 2024-11-29 19:07
I am also not 100% sure and of course it's possible that it's a problem with soularr. The reason I'm leaning towards it being something with your setup is that a bunch of other people have reported that it works and I also can't recreate the problem on my end.

**Comment by yroyathon** [comment] 2024-11-30 17:26
Ok I've run it a while now, I did see the new logging entries you added in the log for the downloads/times it did Not get stuck, ie...
[INFO|soularr|L373] 2024-11-29T18:44:38-0600: Current timeout: 10 - Stalled timeout: 3600
[INFO|soularr|L373] 2024-11-29T18:44:48-0600: Current timeout: 20 - Stalled timeout: 3600
[INFO|soularr|L373] 2024-11-29T18:44:58-0600: Current timeout: 30 - Stalled timeout: 3600

 But for when it does get stuck, those statements don't even get printed to the log, somehow that new timeout logic is not getting activated, but soularr is still running.
last lines from the log from yesterday...
[INFO|soularr|L58] 2024-11-29T23:15:48-0600: Found match from user: chilony for 16 tracks!
[INFO|soularr|L59] 2024-11-29T23:15:48-0600: Average sequence match ratio: 0.8125287125326405
[INFO|soularr|L60] 2024-11-29T23:15:48-0600: SUCCESSFUL MATCH
[INFO|soularr|L61] 2024-11-29T23:15:48-0600: -------------------

then the new log entry after I cancelled the download...
WARNING|soularr|L231] 2024-11-30T00:43:49-0600: Error enqueueing tracks! Adding chilony to ignored users list

last lines from the log today...
[INFO|soularr|L195] 2024-11-30T03:20:04-0600: Parsing result from user: yeeboi0
[INFO|soularr|L58] 2024-11-30T03:20:05-0600: Found match from user: yeeboi0 for 16 tracks!
[INFO|soularr|L59] 2024-11-30T03:20:05-0600: Average sequence match ratio: 0.6249505288525782
[INFO|soularr|L60] 2024-11-30T03:20:05-0600: SUCCESSFUL MATCH
[INFO|soularr|L61] 2024-11-30T03:20:05-0600: -------------------

processes currently running in the soularr container now...
I have no name!@soularr:/app$ ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1000           1  0.0  0.0   4344   640 ?        Ss   Nov29   0:00 bash run.sh
1000         178  0.0  0.0  45504 29308 ?        S    03:16   0:01 python -u /app/soularr.py
1000         227  0.0  0.0   4608  3200 pts/0    Ss   11:18   0:00 /bin/bash
1000         233  0.0  0.0   8536  4352 pts/0    R+   11:18   0:00 ps aux

**Comment by CurlyBoy** [comment] 2024-12-03 14:39
What about the issue with stuck searches? I know it's ultimately a slskd issue, but it's been a problem for a long time so I don't see it getting fixed any time soon. I have to restart the script anytime a search gets stuck, which for me has been fairly common.

![Screenshot_20241203-083514.png](https://github.com/user-attachments/assets/afe52fd5-bf18-4862-925a-3838b2ebc538)

**Comment by mrusse** [comment] 2024-12-03 15:05
Yeah it is a slskd issue unfortunately but I will be putting out an update soon with a workaround for it. It is very hard to test for me since I don't get stuck searches very often. I will put out an update over the weekend or early next week to address it though.

**Comment by mrusse** [comment] 2024-12-03 15:06
Going to close this issue for now since only @yroyathon has had issues with it. Yroyathon maybe you can join the discord at some point and we can debug your setup together. Thanks.

**Closed** 2024-12-03 15:06 UTC

**Comment by yroyathon** [comment] 2024-12-03 16:24
I appreciate the time and attention on this.  But I was eventually able to build a workaround script, it runs in a crontab 1x/hour, so I'm good. 
My script passes a "ps aux" command to the docker container to see the running processes, then computes soularr's runtime.  If it's longer than some limit (2 hours), than it runs a different script which uses slskd_api to cancel any Queued or InProgress downloads in Soulseek.  That allows soularr to proceed.
